app.name: Search and Filter Microservice

#DATASOURCE
spring.datasource:
  url: jdbc:mysql://ugd-business-listing-rds.c9v9opuetitb.ap-southeast-1.rds.amazonaws.com:3306/businesslistingrds
  username: admin
  password: nusissteam29
  # driver-class-name: com.mysql.jdbc.Driver

#LOGGING
logging.level.org.springframework:
  jdbc.core:
    JdbcTemplate: TRACE
    StatementCreatorUtils: TRACE
  web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR